#!/bin/bash

#SBATCH --job-name=exp2_TFT

#SBATCH --gres=gpu:1

#SBATCH --qos=normal

#SBATCH --mem=10G

#SBATCH --output=./slurm_logs/exp2_TFT-%j.out

#SBATCH --error=./slurm_logs/exp2_TFT-%j.err

#SBATCH --time=15:00:00

#SBATCH --mail-type=END,FAIL


echo Running on $(hostname)

source /h/kupfersk/cfpr_2025/cfpr_2025/miniconda3/etc/profile.d/conda.sh
conda activate cfpr_2025_py3.8


cd /h/kupfersk/cfpr_2025/generate_forecasts

#ipython
#jupyter nbconvert --to notebook --execute /h/kupfersk/cfpr_2025/generate_forecasts/autogluon_generate_exp2_Individual_TFT.ipynb

python /h/kupfersk/cfpr_2025/generate_forecasts/autogluon_generate_exp2_Individual_TFT.py

